# Get location googLE
GET https://maps.googleapis.com/maps/api/geocode/json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA&key=AIzaSyB2wVWUghp_ggsdMzMYmYPEqcNosqlplYg HTTP/1.1
Content-Type: application/json